<?php
/*
Plugin Name: My Custom CSS
Plugin URI: https://wordpress.org/plugins/my-custom-css/
Description: With this plugin you can put custom css code without edit your theme and/or your plugins (really useful in case of any theme/plugin update).
It contain also <a href="https://ace.c9.io/">Ace (Ajax.org Cloud9 Editor)</a> Code Editor for write a good css code.
You can see in action (source code) here: <a href="http://vegamami.altervista.org/">VegAmami</a> :)
PS: support file backup and - very important - static css file (fantastic for performance) ;)
Author: Salvatore Noschese - DarkWolf
Version: 2.3
Author URI: https://laltroweb.it/
Text Domain: my-custom-css
*/

// Prevent Direct Access with homepage redirect
if (!defined('DB_NAME'))
{
	header('Location: http://'.$_SERVER['SERVER_NAME'].'/');
}

function mystylecss_basedir()
{
	$upload_dir = wp_upload_dir();
	$mystylecss_basedir = $upload_dir['basedir'];
	return $mystylecss_basedir;
}
function mystylecss_url()
{
	$upload_dir = wp_upload_dir();
	$mystylecss_url = $upload_dir['baseurl'];
	return $mystylecss_url;
}

 
// Obtain the path to the admin directory.
function my_custom_css_get_admin_path()
{
	// Replace the site base URL with the absolute path to its installation directory. 
	$admin_path = str_replace( get_bloginfo( 'url' ) . '/', ABSPATH, get_admin_url() );
	
	// Make it filterable, so other plugins can hook into it.
	$admin_path = apply_filters( 'my_custom_css_get_admin_path', $admin_path );
	return $admin_path;
}

// Fix old backup folder or no exist
if (!is_dir(mystylecss_basedir().'/my_custom_css/bkk'))
{
	wp_mkdir_p(mystylecss_basedir().'/my_custom_css/bkk');
}
// And Blank index.html to prevent listing directory
else if(!file_exists(mystylecss_basedir()."/my_custom_css/index.html") || !file_exists(mystylecss_basedir()."/my_custom_css/bkk/index.html"))
{
	file_put_contents(mystylecss_basedir()."/my_custom_css/index.html", "<!-- Blank index.html to prevent listing directory -->");
	file_put_contents(mystylecss_basedir()."/my_custom_css/bkk/index.html", "<!-- Blank index.html to prevent listing directory -->");
}

// Generate my_style_id url:
function my_style_id()
{
	$blog_id = get_current_blog_id(); $cssid = ( $blog_id > "1" ) ? $cssid = "_id-".$blog_id : $cssid = null;
	$my_style_id = "/my_custom_css/my_style".$cssid.".css";
	return $my_style_id;
}

// Generate css url:
function css_url()
{
	$css_url = mystylecss_url().my_style_id();
	return $css_url;
}

// Generate css path:
function css_path()
{
	$css_path = mystylecss_basedir().my_style_id();
	return $css_path;
}

// make my_style.css and write write css code!
function mycustomcss()
{
	// Strip tag for security reason!
	$mycustomcss = strip_tags(get_option('my_custom_css'));
	return $mycustomcss;
}

function mycustomcss_head()
{
	$mycustomcss = mycustomcss();
	if (!empty($mycustomcss))
	{
		// Write in source!
		echo "\n<!-- My Custom CSS -->\n<link rel='stylesheet' id='my-custom-css' href='".css_url()."?".@filemtime(css_path())."' type='text/css' media='all' />\n<!-- My Custom CSS -->\n";
	}
}

function makecss()
{
	$makecss = file_put_contents(css_path(), "/********* Do not edit this file *********/\n/*\nMy Custom CSS - Maked by Salvatore Noschese\na.k.a. DarkWolf - http://www://darkwolf.it/\n*/\n/********* Do not edit this file *********/\n\n".mycustomcss());
	return $makecss;
}

// Fix first upgrade from old release or manual my_style.css deletion!
if (!file_exists(css_path()))
{
	makecss();
}

// Start Add link on plugins page
function mycustomcss_links($links)
{ 
	# Settings:
	$settings_link = '<a href="admin.php?page=my_custom_css" title="My Custom CSS">'.__('Settings','my-custom-css').'</a>';
	array_unshift($links, $settings_link);
	# Support:
	$support_forum = '<a href="https://laltroweb.it/" title="laltroweb.it">'.__('Support','my-custom-css').'</a>';
	array_unshift($links, $support_forum);
	# return:
	return $links;
}
function add_plugin_meta_links($links, $file)
{
	if ($file == plugin_basename(__FILE__))
	{
		$links[] = '<a href="https://www.paypal.me/SalvatoreN" title="Buy Me a Beer ;)">Donate :)</a>';
	}
	return $links;
}
// End Add link on plugins page


// Icon in base 64
function mycustomcss_data_icon()
{
	$mycustomcss_data_icon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAnNJREFUeNqUU01IVFEU/u77m7/GRqqhbbUpnVAYIULIRoMwmjApaNGiVgViJErUolpE2KKFEIGGi4JK0wpjtCCKqChQxmYKiwojaSW0GJkabGbevNe59zxRalPvvfPuPeee853fK6YubM85FSfiOi7+5xGagKZrC4Y03nY4CdgOoDAEfWJZ03WVyPsR7/DW0DB5MxUxlOfiIvD+CisrAAPQiBybZBXpjsikvc0kPdV2Qtoaysj+ATTdB6It7OX7S+BFuydrYtm9KLBjBf+uSzk0FJpdYOO7a8gzeWqfJw2NlUerKdwQsRbzIxHADAKbDqhUNc6rxKjWasC/DpiooX2YZTsfADr50S3mEykC9HmpLAHA5kUeKPIzwMRm0tGBfXMsf7iFVvKe/EryCiyqjaaKJiurCk3pOL+A3W8oZDI0A8DU0WVwXxWQOYGa8wJ1qWsIw5I1ENyWXBpo/cjKOQLQqRbNaeYXMpx34jVqzwpc79kPQ/hxZGCIAGSLZI4zp2mlYpXzXLBAFLFzQtV4Zg/NiX89YmR8o+cQMq+GEWvcy4HJiYKPQNxqnoPAWtXzrakhDHaTIWUX70upKAe725DNDkOnRnT2j+NOsRmGK5CfHJmtWhplQa+fApMRF908Zj89x+WOhDr78HkMJjXq6mPgNhnnRTkvs687ldxYX7LlyHkD68ApLrqlbOvc6LE26lGZS2FSZgNjQP2jDQfDYS14afzLW6QvNsozSh7BP4h6iXhLL9xb35h29arbEvfOQtLWkNa0Kay8aRrFEXJNHF/1bPrpSTRYOlQ7npxBQ6IP0/0/EyiIMgX67zc47tFfz28BBgBxJMx44bFMEAAAAABJRU5ErkJggg==';
	return $mycustomcss_data_icon;
}

// Change the CSS for this plugin on admin plugins page
function mycustomcss_admin_style()
{
	global $pagenow;
	if ($pagenow == "plugins.php")
	{
		echo "<style type='text/css'>\n#my-custom-css td.plugin-title strong {\n\tbackground: url(".mycustomcss_data_icon().") no-repeat scroll 115px 2px;\n}\n#my-custom-css div.row-actions-visible {\n\tpadding-top: 15px;\n}\n#my-custom-css div.plugin-version-author-uri {\n\tbackground-color: #EAEAEA;\n\tborder-radius: 5px;\n\tbox-shadow: 0 8px 6px -6px gray; \n\tfont-weight: bold; \n\tpadding: 7px; \n\tmargin-bottom: 12px;\n}\n</style>\n";
	}
}


// Make backup when save!
if(isset($_POST['save']))
{
	$directory = mystylecss_basedir()."/my_custom_css/bkk/*.css";
	if (glob($directory) != false)
	{
		$filecount = count(glob($directory))+1;
	}
	else
	{
		$filecount = 1;
	}
	$oldname = css_path();
	$newname = mystylecss_basedir().'/my_custom_css/bkk/' . ( $filecount ++ ) . $cssid . '_' . filemtime($oldname) .'.css';
	rename($oldname, $newname);
}

// View backup (view only css)
if(isset($_POST['viewbackup']))
{
	$directory = mystylecss_basedir()."/my_custom_css/bkk/";
	$files=array();
	if ($dh=opendir($directory))
	{
		while (($file=readdir($dh))!==false)
		if ($file!="." && $file!=".." && preg_match("/\.(css)$/", $file))
			$files[filemtime($directory.$file)]=$file;
		closedir($dh);
	}

	krsort($files);
	reset($files);
	$href = mystylecss_url()."/my_custom_css/bkk/";
	date_default_timezone_set(ini_get('date.timezone') ? ini_get('date.timezone') : 'UTC');

echo '
<!DOCTYPE html>
<html>
  <head>
    <title>My custom CSS - Backup</title>
  </head>
	<body style="background: #F1F1F1; padding: 20px; width: 90%; margin: 20px auto; border: 1px 0 dotted gray">';
	if (glob($directory."*.css") == false)
	{
	echo '
	<input type="button" value="Close now!" onclick="self.close()" style="margin: 0px 20px; float: right" />
	<br />
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
		I can\'t list any *.css: "No file found"... 
	</div>';
	}
	else
	{
	echo '
	<form method="post" action="'. admin_url( 'admin.php' ) .'?action=my_custom_css?erase_backup" style="margin-right: 20px; float: right">
		<input type="button" value="Close now!" onclick="self.close()" style="padding: 2px 5px" />
		 | 
		<input type="submit" name="erasebackup" class="button" value="Erase backup" style="color: red; padding: 2px 5px" onclick="return confirm(\'Do you want really delete all backup?\');" />
	</form>
	<br />';
	while (list($date,$file)=each($files))
	echo '
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
	<p><b>File:</b> <a href="'.$href.$file.'">'.$href.$file.'</a></p>
	<p><b>Path:</b> '.$directory.$file.'</p>
	<p><b>Saved:</b> '.date("M d Y | h:i:s (a)",current_time($date)).'</p>
	<p><b>Size:</b> '.(round(filesize($directory.$file). " bytes")).' bytes</p>
	</div>';
	}
	echo '
  </body>
</html>';
}


// Erase backup:
if(isset($_POST['erasebackup']))
{
echo '
<!DOCTYPE html>
<html>
  <head>
    <title>My custom CSS - Erase Backup</title>
  </head>
	<body style="background: #F1F1F1; padding: 20px; width: 90%; margin: 20px auto; border: 1px 0 dotted gray">';
	$glob = glob(mystylecss_basedir()."/my_custom_css/bkk/*.css");
	if ($glob == false)
	{
	echo '
	<input type="button" value="Close now!" onclick="self.close()" style="margin: 0px 20px; float: right" />
	<br />
	<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
		I can\'t delete any *.css: "No file found"... 
	</div>';
	}
	else
	{
		echo '
		<input type="button" value="Close now!" onclick="self.close()" style="margin: 0px 20px; float: right" />
		<br />';
		foreach (glob(mystylecss_basedir()."/my_custom_css/bkk/*.css") as $filename)
		{
		echo '
		<div style="border: 1px dotted gray; margin: 20px; padding: 10px; background: #fff">
			'.$filename.' - ' . filesize($filename) . 'bytes was successfully deleted!!!
		</div>';
		unlink($filename);
		}
	}
		echo '
  </body>
</html>';
}



// Admin section:
function mycustomcss_admin()
{
	$plugin_page = add_menu_page(__('My Custom CSS Panel','my-custom-css'),__('My Custom CSS','my-custom-css'), 'manage_options', 'my_custom_css', 'mccss_options', mycustomcss_data_icon(), 61);
	add_action('admin_init', 'mycustomcss_registersetting');
	add_action('admin_head-'. $plugin_page, 'mycustomcss_scripts');
	// Disable "WP Editor" in this page if is active: http://wordpress.org/extend/plugins/wp-editor/
	If (is_plugin_active("wp-editor/wpeditor.php") && $_SERVER['QUERY_STRING'] == 'page=my_custom_css')
	{
		function remove_wpeditor_header_info()
		{
		// Wp Editor Style
		wp_deregister_style('wpeditor');
		wp_deregister_style('fancybox');
		wp_deregister_style('codemirror');
		wp_deregister_style('codemirror_dialog');
		wp_deregister_style('codemirror_themes');
		// Wp Editor Script
		wp_deregister_script('wpeditor');
		wp_deregister_script('wp-editor-posts-jquery');
		wp_deregister_script('fancybox');
		wp_deregister_script('codemirror');
		wp_deregister_script('codemirror_php');
		wp_deregister_script('codemirror_javascript');
		wp_deregister_script('codemirror_css');
		wp_deregister_script('codemirror_xml');
		wp_deregister_script('codemirror_clike');
		wp_deregister_script('codemirror_dialog');
		wp_deregister_script('codemirror_search');
		wp_deregister_script('codemirror_searchcursor');
		wp_deregister_script('codemirror_mustache');
		}
	add_action('admin_init', 'remove_wpeditor_header_info', 20);
	}
}

// Check if is mobile!!!
function check_mobile()
{
	$useragent = $_SERVER['HTTP_USER_AGENT'];
	if(preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i',$useragent)||preg_match('/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i',substr($useragent,0,4)))
	{
		$mobile = "Yes";
	}
	else
	{
		$mobile = "";
	}
	return $mobile;
}

// Option page code:
function mycustomcss_scripts()
{
	$mobile = check_mobile();
	if ($mobile != "Yes")
	{
		// Function Load jQuery
		function mycustomcss_scrool_jquery()
		{
			wp_enqueue_script('jquery');
		}
		echo '
		<script type="text/javascript">
		jQuery(document).ready(function($)
		{
			$(window).scroll(function()
			{
				if ($(this).scrollTop() > 100)
				{
					$(\'.scrollup\').fadeIn();
				}
				else
				{
					$(\'.scrollup\').fadeOut();
				}
			});
			$(\'.scrollup\').click(function()
			{
				$("html, body").animate({ scrollTop: 0 }, 600);
				return false;
			});
		});
		</script>
		<style type="text/css">
		.scrollup
		{
			width:40px;
			height:40px;
			opacity:0.3;
			position:fixed;
			bottom:20px;
			right:25px;
			display:none;
			z-index: 10000;
			text-indent:-9999px;
			background-image: url(\'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAAepJREFUeNrcmbFKw0AYx39WKAgOQXAS5AQf4EAQuhWfoIPQZ/ANBEEq+ACFTk43CFJxKIU+hSAtguAgBF2cSganDnIuFwnBhtzljFf/8E1JLr98X+7j7n9ruGsX6AIHwD4ggXVz7ROYATFwD9wCb9SgLeACeAS0ZTyaZ7d+A2wTOAM+HMDy8WHG2vQFdwy8ewDLx7sZ21nrQP8XwPLRz/y7pbUBjGuAS2Ns3lk6c3XCZSFLZbL/B3DZcheq+4dwaXSLetw8AMD5sl45CAAujUEebgdYBAS4MEw0DOAJ0CQcNQ3Td1t5DSh7abymbecwQLg0DhvAkY+aSCmJ4xitNUopoijyMewRwLDql0opdZIkOqvpdKqjKKqawSHAk284j5BPVGnORXCeIOe49r8ycB4gF06ANnAVIRfWJRZCLIVTShXCj0YjpxJbTZJer7cUrkyGXSbJnc1DnU6nEK4IMo5jW8A7gFPbf1ApVQj3E2SSJFpKaQt4CtBymcVCCC2EKHVvu912bTOt4BcLDWNTXBOebgxb2AvWlVnyr8SmKfhtZwilHvwL6yM1jyY1wk1szKNsJq9qgLtysd9WwsDMW8DnHi3gc58WcFbbxgh32Wg9A5dmjNJaqwC798MxRFYz4AV4MMcQsctLvgYA2It91Klq2nkAAAAASUVORK5CYII=\');
			outline: none !important;
		}
		</style>';
	add_action('init', 'mycustomcss_scrool_jquery');
	}
echo '
<!-- Ace Support Start -->
<script language="javascript" src="'.plugin_dir_url(__FILE__).'scripts/ace.js" charset="utf-8"></script>
<script language="javascript" src="'.plugin_dir_url(__FILE__).'scripts/custom-mode.js" charset="utf-8"></script>
<!-- Ace Support End -->
<style type="text/css">
p#footer-upgrade
{
	float: left;
	padding-left: 5px;
	font-style: italic;
}
div#wpfooter
{
	position: relative;
}
</style>';
}


// Register Settings
function mycustomcss_registersetting()
{
	register_setting('mccss_settings','my_custom_css');
}


// Textarea/Form:
function mccss_options()
{

// Get plugin version:
$plugin_data = get_plugin_data(__FILE__);
$plugin_version = $plugin_data['Version'];

// If no backup exist, disable button!
$glob = glob(mystylecss_basedir()."/my_custom_css/bkk/*.css");
if ($glob == false)
{
	$submit_backup = " value=\"No backup here...\" title=\"No backup found...\" disabled";
}
else
{
	$submit_backup = " value=\"View backup :)\" title=\"Click to view all backup!\" ";
}

$mobile = check_mobile(); if ($mobile != "Yes") { $no_mobile = '<a href="#" class="scrollup">^Top</a>'; } // Totop only if Not mobile!
echo '
<div class="wrap">
	<h2>' .  __('My Custom CSS Panel','my-custom-css') . ' - v'.$plugin_version.'</h2>
	<form id="my-custom-css" method="post" action="options.php">';
	settings_fields( 'mccss_settings' );
echo '
	<p>' .  __('Custom CSS Code:','my-custom-css') . '
		<input type="submit" name="save" class="button-primary" value="' .  __('Save','my-custom-css') . '" style="height: 50px; width: 150px; position: fixed; right: 25px; z-index: 5; font-size: 30px; top: 45px;" />
	</p>
		<div id="my_custom_css_container">
			<div name="my_custom_css" id="my_custom_css" style="border: 1px solid #DFDFDF; -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px; width: 100%; height: 400px; position: relative;"></div>
		</div>
		<textarea id="my_custom_css_textarea" name="my_custom_css" style="display: none;">'.get_option('my_custom_css').'</textarea>
		<p><!-- Smooth Scroll by DarkWolf -->'.$no_mobile.'<!-- Smooth Scroll by DarkWolf --></p>
	</form>
</div>';

// Hidden view/erase button for blog id > 1 (security fix in multisite)
$blog_id = get_current_blog_id();
if($blog_id == 1)
{
echo '
	<form method="post" action="'.admin_url( 'admin.php' ).'?action=my_custom_css?show_backup" target="_blank">
		<input type="submit" name="viewbackup" class="button-secondary" style="float: left;"'.$submit_backup.' />
	</form>';
}
echo '
</div>';

	// Ok, save css!!!		
	makecss();

}

add_action('admin_menu', 'mycustomcss_admin');
add_action('wp_head', 'mycustomcss_head', 99999);
add_action('admin_print_styles', 'mycustomcss_admin_style');
add_filter('plugin_row_meta', 'add_plugin_meta_links', 10, 2);
add_filter('plugin_action_links_'.plugin_basename(__FILE__).'', 'mycustomcss_links');
load_plugin_textdomain('my-custom-css', false, dirname(plugin_basename(__FILE__)) . '/lang/');


?>